# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-01 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 4, 1, 16, 5, 8, 5137, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
